name: 'airline_performance'
version: '1.0.0'
config-version: 2

profile: 'airline_performance'

model-paths: ['models']

models:
  airline_performance:
    staging:
      +materialized: view

    gold:
      +materialized: table