{{ config(materialized='view') }}

SELECT

    FL_DATE,

    EXTRACT(YEAR FROM CAST(FL_DATE AS DATE)) AS YEAR,
    EXTRACT(MONTH FROM CAST(FL_DATE AS DATE)) AS MONTH,
    EXTRACT(QUARTER FROM CAST(FL_DATE AS DATE)) AS QUARTER,
    EXTRACT(DAYOFWEEK FROM CAST(FL_DATE AS DATE)) AS DAY_OF_WEEK,
    OP_CARRIER,
    OP_CARRIER_FL_NUM,
    ORIGIN,
    DEST,
    DEP_DELAY,
    ARR_DELAY,
    CANCELLED,
    CANCELLATION_CODE,
    DIVERTED,
    CARRIER_DELAY,
    WEATHER_DELAY,
    NAS_DELAY,
    SECURITY_DELAY,
    LATE_AIRCRAFT_DELAY,
    DISTANCE,
    CRS_ELAPSED_TIME,
    ACTUAL_ELAPSED_TIME,
    AIR_TIME,
    IS_DELAYED_ARR

FROM read_parquet(
    '../data/parquet_clean/*.parquet'
)